config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  # get 'companies/index'
  devise_for :users

  authenticated :user do
    root to: 'companies#index', as: :authenticated_root
  end

  root to: "pages#home"

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :companies do
    resources :reports, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :report_questions, only: [:show, :edit, :update]
    end
  end

  get "/companies/:company_id/reports/:id/action_plan", to: "reports#action_plan", as: :action_plan
  get "/companies/:company_id/reports/:id/fire_alarm", to: "reports#fire_alarm", as: :fire_alarm
  get "/companies/:company_id/reports/:id/fire_training", to: "reports#fire_training", as: :fire_training
  get "/companies/:company_id/reports/:id/fire_extinguishers", to: "reports#fire_extinguishers", as: :fire_extinguishers
  get 'profile', to: 'profiles#show'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch 'profile', to: 'profiles#update'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  after_action :verify_authorized, except: [:index, :show], unless: :skip_pundit?

  def show
    authorize @user
  end

  def edit
    authorize @user
  end

  def update
    authorize @user

    if @user.update(user_params)
      redirect_to profile_path, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :telephone_number)
  end
end

app/views/profiles/edit.html.erb
<div class="container mt-5">
  <h1>Edit Profile</h1>

  <%= form_with(model: @user, url: profile_path, local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
      <div class="col-md-12">
        <div class="form-group textOnInput mt-3">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: "free-text-input-big" %>
        </div>
        <div class="form-group textOnInput mt-3">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: "free-text-input-big" %>
        </div>
        <div class="form-group textOnInput mt-3">
          <%= form.label :email %>
          <%= form.text_field :email, class: "free-text-input-big" %>
        </div>
        <div class="form-group textOnInput mt-3">
          <%= form.label :telephone_number %>
          <%= form.text_field :telephone_number, class: "free-text-input-big" %>
        </div>

        <div class="d-flex justify-content-between mt-3">
          <div>
            <%= link_to 'Back', companies_path, class: 'btn-big-dark' %>
          </div>
          <div class="justify-content-end">
            <%= form.submit 'Save Changes', class: 'btn-big' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container mt-5">
  <h1>User Profile</h1>
  <%= form_with(model: @user, url: user_path(@user), local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
      <div class="col-md-12">
        <div class="form-group textOnInput mt-3">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: "free-text-input-big", readonly: true %>
        </div>
        <div class="form-group textOnInput mt-3">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: "free-text-input-big", readonly: true %>
        </div>
        <div class="form-group textOnInput mt-3">
          <%= form.label :email %>
          <%= form.text_field :email, class: "free-text-input-big", readonly: true %>
        </div>
        <div class="form-group textOnInput mt-3">
          <%= form.label :telephone_number %>
          <%= form.text_field :telephone_number, class: "free-text-input-big", readonly: true %>
        </div>
        <div class="d-flex justify-content-between mt-3">
          <div>
            <%= link_to 'Back', companies_path, class: 'btn-big-dark' %>
          </div>
        <%= link_to 'Edit Profile', edit_profile_path(@profile), class: "btn-big" %>
</div>

</div>
  <% end %>
</div>