config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  # get 'companies/index'
  devise_for :users

  authenticated :user do
    root to: 'companies#index', as: :authenticated_root
  end

  root to: "pages#home"

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :companies do
    resources :reports, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :report_questions, only: [:show, :edit, :update]
    end
  end

  get "/companies/:company_id/reports/:id/action_plan", to: "reports#action_plan", as: :action_plan
  get "/companies/:company_id/reports/:id/fire_alarm", to: "reports#fire_alarm", as: :fire_alarm
  get "/companies/:company_id/reports/:id/fire_training", to: "reports#fire_training", as: :fire_training
  get "/companies/:company_id/reports/:id/fire_extinguishers", to: "reports#fire_extinguishers", as: :fire_extinguishers
  get 'profile', to: 'profiles#show'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch 'profile', to: 'profiles#update'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer">
    <div class="links">
      <a href="#"><i class="fab fa-fw fa-facebook-f"></i></a>
      <a href="#"><i class="fab fa-fw fa-twitter"></i></a>
      <a href="#"><i class="fab fa-fw fa-instagram"></i></a>
      <p>Team Flare Risk <i class="fas fa-fire"></i></p>

    </div>
  </div>

app/views/shared/_free_text_input.html.erb
<div class="form-group textOnInput">
  <%= form.label :attribute %>
  <%= form.text_field :attribute, class: "free-text-input" %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "flare-logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <!--
            <li class="nav-item active">
              <%= link_to "Home", "/", class: "nav-link" %>
            </li>
          -->
          <li class="nav-item">
            <%= link_to "All Companies", companies_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="text-dark fs-2 ms-5" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa-solid fa-bars ml-2 mt-2 pt-1"></i>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <!--
                <%= link_to "Home", root_path, class: "dropdown-item" %>
              -->
              <%= link_to "All companies", companies_path, class: "dropdown-item" %>
              <% if current_user.inspector? %>
                <%= link_to 'List a company', new_company_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "My Profile", profile_path, class: "dropdown-item" %>

            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_primary_button.html.erb
<%= button_tag class: 'button-primary button-primary:hover' do %>
  <%= yield %>
<% end %>

app/views/shared/_secondary_button.html.erb
<%= button_tag class: 'button-secondary button-secondary:hover' do %>
  <%= yield %>
<% end %>