config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  # get 'companies/index'
  devise_for :users

  authenticated :user do
    root to: 'companies#index', as: :authenticated_root
  end

  root to: "pages#home"

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :companies do
    resources :reports, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :report_questions, only: [:show, :edit, :update]
    end
  end

  get "/companies/:company_id/reports/:id/action_plan", to: "reports#action_plan", as: :action_plan
  get "/companies/:company_id/reports/:id/fire_alarm", to: "reports#fire_alarm", as: :fire_alarm
  get "/companies/:company_id/reports/:id/fire_training", to: "reports#fire_training", as: :fire_training
  get "/companies/:company_id/reports/:id/fire_extinguishers", to: "reports#fire_extinguishers", as: :fire_extinguishers
  get 'profile', to: 'profiles#show'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch 'profile', to: 'profiles#update'

end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :inspector, class_name: 'User', :foreign_key => :inspector_id
  belongs_to :client, class_name: 'User', :foreign_key => :client_id
  has_many :reports, dependent: :destroy
  geocoded_by :address
  after_validation :geocode
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = policy_scope(Company)
    @companies = Company.all unless @companies
    if params[:query].present? && !params[:query].empty?
      @companies = @companies.where("name ILIKE ?", "%#{params[:query]}%")
    end
    respond_to do |format|
      format.html
      format.text { render partial: "companies/list", locals: {companies: @companies}, formats: [:html] }
    end

    @markers = @companies.geocoded.map do |company|
      {
        lat: company.latitude,
        lng: company.longitude
      }
    end
  end

  def show
    authorize(@company)
    @reports = @company.reports unless @reports
    if params[:query].present? && !params[:query].empty?
      @reports = @company.reports.where("premises_name ILIKE ?", "%#{params[:query]}%")
    end
      respond_to do |format|
        format.html
        format.text { render partial: "companies/list2", locals: {reports: @reports}, formats: [:html] }
      end


    @markers = [{
      lat: @company.latitude,
      lng: @company.longitude
    }]
  end

  def new
    @company = Company.new
    authorize @company
  end

  def create
    @company = Company.new(company_params)
    @company.inspector_id = current_user.id
    # @company.user_id = current_user.id
    @client = User.where(client_params).first
    @company.client_id = @client.id if @client.present?
    authorize @company
    if @company.save
      redirect_to company_path(@company)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize(@company)
  end

  def update
    authorize(@company)
    if @company.update(company_params)
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    authorize @company
    if @company.destroy
      redirect_to companies_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :address, :telephone_number, :email_address)
  end

  def client_params
    params.require(:company).permit(:email)
  end

  def set_company
    @company = Company.find(params[:id])
  end
end

app/views/companies/_form.html.erb
<%= form_with(model: @company, id: "myform") do |form| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
    <div class="col-md-8">

      <div class="form-group textOnInput mt-3">
        <%= form.label :name, "Company Name" %>
        <%= form.text_field :name, class: "free-text-input-big" %>
      </div>

      <div class="form-group textOnInput mt-3">
        <%= form.label :address %>
        <%= form.text_field :address, class: "free-text-input-big"  %>
      </div>

      <div class="form-group textOnInput mt-3">
        <%= form.label :telephone_number %>
        <%= form.text_field :telephone_number, class: "free-text-input-big" %>
      </div>

      <div class="form-group textOnInput mt-3">
        <%= form.label :email_address, "Company Email" %>
        <%= form.text_field :email_address, class: "free-text-input-big" %>
      </div>

      <div class="form-group textOnInput mt-3">
        <%= form.label :client_email_address, "Client Email" %>
        <%= form.text_field :email, class: "free-text-input-big" %>
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-between">
    <div>
      <%= link_to 'Back', companies_path, class: 'btn-big-dark' %>
    </div>
    <div class="actions justify-content-end">
      <%= form.submit class: "btn-big", form: "myform"%>
    </div>
  </div>
<% end %>





<%# <% end %>

<%# <%= simple_form_for(company) do |f| %>
  <%# <%= f.input :name %>
  <%# <%= f.input :address %>
  <%# <%= f.input :telephone_number %>
  <%# <%= f.input :email_address %>
  <%# <%= f.input :client_id %>
  <%# <%= f.submit "Create", class: "ms-1 btn btn-dark" %>
<%# <% end %>

app/views/companies/_list.html.erb
<tbody data-insert-in-list-target="list">
  <% num = 0 %>
  <% @companies.sort.each do |company| %>
    <tr>
      <th scope="row"><%= num += 1 %></th>
      <td><%= company.name %></td>
      <td><%= company.address %></td>
      <td><%= company.email_address %></td>
      <td><%= company.telephone_number %></td>
      <td><%= link_to 'View', company_path(company), class: "btn"%></td>
    </tr>
  <% end %>
</tbody>

app/views/companies/_list2.html.erb
      <tbody data-insert-in-list-target="list">
        <% num = 0 %>
        <% @reports.sort.each do |report| %>
          <tr>
            <th scope="row"><%= num += 1 %></th>
            <td><%= report.premises_name %></td>
            <td><%= report.street_address %></td>
            <td><%= report.telephone_number %></td>
            <td><%= report.date_report_completed %></td>
            <% if current_user.inspector? %>
            <td><%= link_to 'Edit', edit_company_report_path(@company, report), class: "btn"%></td>
            <% else %>
            <td></td>
            <% end %>
            <td><%= link_to 'View', company_report_path(@company, report), class: "btn"%></td>
            <%# <td><%= link_to 'X', company_report_path(@company, report), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-button" %>
            <td><%= link_to '<i class="fas fa-trash"></i>'.html_safe, company_report_path(@company, report), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-button" %></td>
          </tr>
        <% end %>
      </tbody>

app/views/companies/edit.html.erb
<div class="container mt-5">
  <h1>Edit Company</h1>

  <%= form_with(model: @company, local: true) do |form| %>
    <% if @company.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@company.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
        <% @company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
      <div class="col-md-8">

        <div class="form-group textOnInput mt-3">
          <%= form.label :name %>
          <%= form.text_field :name, class: "free-text-input-big" %>
        </div>

        <div class="form-group textOnInput mt-3">
          <%= form.label :email_address %>
          <%= form.text_field :email_address, class: "free-text-input-big"  %>
        </div>

        <div class="form-group textOnInput mt-3">
          <%= form.label :telephone_number %>
          <%= form.text_field :telephone_number, class: "free-text-input-big" %>
        </div>
        <div class="form-group textOnInput mt-3">
          <%= form.label :address %>
          <%= form.text_field :address, class: "free-text-input-big" %>
        </div>
      </div>
    </div>

  <div class="d-flex justify-content-between mt-4">
    <div>
      <%= link_to 'Back', company_path(@company), class: "btn-big-dark"%>
    </div>
    <div class="justify-content-end">
      <% if current_user.inspector? %>
        <%= form.submit class: "btn-big"%>
      <% end %>
    </div>
  </div>
</div>
  <% end %>

app/views/companies/index.html.erb
<div data-controller="insert-in-list">
  <div class="container mt-5">
    <div class="row justify-content-between">
      <div class="col-lg-6">
        <h1 class="mb-3">All Companies</h1>
      </div>
      <div class="col-lg-6">
        <div class="row justify-content-end">
          <%= form_with url: companies_path, method: :get, class: "d-flex", data: { insert_in_list_target: "form", action: "submit->insert-in-list#send" } do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control mr-2",
                  placeholder: "Type a company",
                  data: {
                    insert_in_list_target: 'searchInput'
                  }
              %>
            <%= submit_tag "Search", name: "", class: "btn" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
    <div class="col-lg-12">
      <table class="table table-striped mt-5">
        <thead>
          <tr>
            <th scope="col">*</th>
            <th scope="col">Company name</th>
            <th scope="col">Company address</th>
            <th scope="col">Email</th>
            <th scope="col">Tel</th>
            <th scope="col"></th>
          </tr>
        </thead>
          <%= render 'list', companies: @companies %>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-between mt-4">
    <div>
      <%= link_to 'Back', root_path, class: 'btn-big-dark' %>
    </div>
    <div class="justify-content-end">
      <% if current_user.inspector? %>
        <%= link_to 'New Company', new_company_path, class: 'btn-big' %>
      <% end %>
    </div>
  </div>
</div>




<%# <div class="row"> %>
    <%# <% @companies.each do |company| %>
      <%# <div class="col-sm-6 col-md-4 col-lg-3"> %>
        <%# <div class="card mb-4"> %>
          <%# <div class="card-body"> %>
            <%# <h5 class="card-title"><%= company.name %>
            <%# <p class="card-text"> %>
              <%# <strong>Address:</strong> <%= company.address %>
              <%# <strong>Email:</strong> <%= company.email_address %>
              <%# <strong>Telephone:</strong> <%= company.telephone_number %>
            <%# </p> %>
            <%# <%= link_to 'Show', company_path(company), class: 'btn btn-primary' %>
          <%# </div> %>
        <%# </div> %>
      <%# </div> %>
    <%# <% end %>
  <%# </div> %>

app/views/companies/new.html.erb
<div class="container mt-5">
  <h1>New Company</h1>
  <div>
    <%= render 'form', company: @company %>
  </div>


</div>

app/views/companies/show.html.erb
<div class="container mt-5">
  <h1><%= @company.name %></h1>

    <%= form_with(model: @company, local: true) do |form| %>
      <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
          <% @company.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
        <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
          <div class="col-md-12">
            <div class="form-group textOnInput">
              <%= form.label :name, "Company Name" %>
              <%= form.text_field :name, class: "free-text-input-big", readonly: true %>
            </div>
            <div class="form-group textOnInput mt-3">
              <%= form.label :email_address %>
              <%= form.text_field :email_address, class: "free-text-input-big", readonly: true  %>
            </div>
            <div class="form-group textOnInput mt-3">
              <%= form.label :telephone_number %>
              <%= form.text_field :telephone_number, class: "free-text-input-big", readonly: true %>
            </div>
            <div class="form-group textOnInput mt-3">
              <%= form.label :address %>
              <%= form.text_field :address, class: "free-text-input-big", readonly: true %>
            </div>
          </div>
          <div class="map col-md-4" data-controller="map"
            id="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
            style="margin-left: 20px;"
            >
          </div>
        </div>
        <%# <div class="actions"> %>
          <%# <%= form.submit class: "btn"%>
        <%# </div> %>
    <% end %>
  <div class="d-flex justify-content-between">
    <% if current_user.inspector? %>
        <%= link_to 'Delete', company_path(@company), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn-big-dark' %>

        <%= link_to 'Edit Company', edit_company_path(@company), class: 'btn-big' %>
    <% end %>
  </div>
  </div>

  <div data-controller="insert-in-list">
   <div class="container mt-5" >
  <div class="row justify-content-between" style="margin-top: 120px;">
      <div class="col-lg-6">
        <h1 class="mb-3">Reports</h1>
      </div>
      <div class="col-lg-6 justify-content-end">
        <div class="row justify-content-end">
         <%= form_with url: company_path, method: :get, class: "d-flex", data: { insert_in_list_target: "form", action: "submit->insert-in-list#send" }, remote: true do %>
          <%= text_field_tag :query,
              params[:query],
              class: "form-control ml-2",
              style: "margin-left: auto; width: 400px; margin-right: 20px",
              placeholder: "Type a premise",
              data: {
                    insert_in_list_target: 'searchInput'
                  }
          %>
          <%= submit_tag "Search", name: "", class: "btn",  style: "margin-right: 40px" %>
          <% end %>
        </div>
      </div>
    </div>


  <div class="row">
    <table class="table table-striped mt-5">
      <thead>
        <tr>
          <th scope="col">*</th>
          <th scope="col">Premises name</th>
          <th scope="col">Premises address</th>
          <th scope="col">Tel</th>
          <th scope="col">Date Completed</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>

      <%= render 'list2', reports: @reports %>

<!--       <tbody>
        <% num = 0 %>
        <% @company.reports.each do |report| %>
          <tr>
            <th scope="row"><%= num += 1 %></th>
            <td><%= report.premises_name %></td>
            <td><%= report.street_address %></td>
            <td><%= report.telephone_number %></td>
            <td><%= report.date_report_completed %></td>
            <% if current_user.inspector? %>
            <td><%= link_to 'Edit', edit_company_report_path(@company, report), class: "btn"%></td>
            <% else %>
            <td></td>
            <% end %>
            <td><%= link_to 'View', company_report_path(@company, report), class: "btn"%></td>
            <td> <%= link_to company_report_path(@company, report), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "delete-button" do %>
              <i class="fas fa-trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody> -->

    </table>
  </div>

  <div class="d-flex justify-content-between mt-4">
    <div>
      <%= link_to 'Back to Companies', companies_path, class: 'btn-big-dark' %>
    </div>
    <div class="justify-content-end">
      <% if current_user.inspector? %>
        <%= link_to 'Create report', new_company_report_path(@company), class: 'btn-big-dark' %>
      <% end %>
    </div>
  </div>
</div>
</div>