config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  # get 'companies/index'
  devise_for :users

  authenticated :user do
    root to: 'companies#index', as: :authenticated_root
  end

  root to: "pages#home"

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :companies do
    resources :reports, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :report_questions, only: [:show, :edit, :update]
    end
  end

  get "/companies/:company_id/reports/:id/action_plan", to: "reports#action_plan", as: :action_plan
  get "/companies/:company_id/reports/:id/fire_alarm", to: "reports#fire_alarm", as: :fire_alarm
  get "/companies/:company_id/reports/:id/fire_training", to: "reports#fire_training", as: :fire_training
  get "/companies/:company_id/reports/:id/fire_extinguishers", to: "reports#fire_extinguishers", as: :fire_extinguishers
  get 'profile', to: 'profiles#show'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'
  patch 'profile', to: 'profiles#update'

end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :company
  has_many_attached :photos
  has_many :report_questions, dependent: :destroy
  has_many :questions, through: :report_questions
  accepts_nested_attributes_for :report_questions

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    [street_address, city, postcode].compact.join(', ')
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_company, only: [:new, :create, :edit, :update, :show, :destroy]

  def new
    @report = Report.new
    # @company = Company.find(params[:company_id])
    authorize @report
  end

  def create
    @report = Report.new(report_params)
    @report.company = @company
    authorize @report
    if @report.save
      @questions = Question.all
      # for every question
      @questions.each do |question|
        @report_question = ReportQuestion.new(answer: false)
        # new instance of report_question
        @report_question.question = question
        # assign the question for example report_question(1) will be assinged question(1)
        @report_question.report = @report
        # assigned to the report we just created
        @report_question.save!
        # save it!
      end
      redirect_to company_report_path(@company, @report)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @report = Report.find(params[:id])
    authorize @report
    @report_questions = @report.report_questions
    @markers = [{
      lat: @report.latitude,
      lng: @report.longitude
    }]
  end

  def fire_alarm
    @report = Report.find(params[:id])
    @company = Company.find(params[:company_id])
    authorize @report
    @report_questions = []
    @report.report_questions.each { |report_question| @report_questions << report_question if report_question.question_id < 4 }
  end

  def fire_training
    @report = Report.find(params[:id])
    @company = Company.find(params[:company_id])
    authorize @report
    @report_questions = []
    @report.report_questions.each { |report_question| @report_questions << report_question if report_question.question_id > 3 && report_question.question_id < 9 }
  end

  def fire_extinguishers
    @report = Report.find(params[:id])
    @company = Company.find(params[:company_id])
    authorize @report
    @report_questions = []
    @report.report_questions.each { |report_question| @report_questions << report_question if report_question.question_id > 8 }
  end

  def edit
    @report = Report.find(params[:id])
    # @company = Company.find(params[:company_id])
    authorize @report
  end

  def update
    @report = Report.find(params[:id])
    # @company = Company.find(params[:company_id])
    authorize @report
    if @report.update(report_params)
      redirect_to action_plan_path(@company, @report)
    else
      render :edit
    end
  end

  def destroy
    @report = Report.find(params[:id])
    authorize @report
    if @report.destroy
      redirect_to company_path(@report.company), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def action_plan
    @report = Report.find(params[:id])
    authorize @report
    @company = @report.company
    @report_questions = @report.report_questions.select do |question|
      question if question.answer == false && question.fault.present?
    end
  end

  private

  def report_params
    params.require(:report).permit(
      :premises_name,
      :street_address,
      :city, :postcode,
      :telephone_number,
      :date_report_completed,
      :construction_details,
      :number_of_floors,
      :floor_area,
      { photos: [] },
      report_questions_attributes: [:id, :answer, :fault, :recommendation, :date, :priority, :question_id, photos: []]
    )
  end

  def set_company
    @company = Company.find(params[:company_id])
  end
end

app/views/reports/_form.html.erb
<%= form_with(model: [@company, @report], data: { insert_in_list_target: "form", action: "submit->insert-in-list#send" }, local: true) do |form| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
    <div class="col-md-8">

      <div class="form-group textOnInput mt-3">
        <%= form.label :date_report_completed, "Date of assessment" %>
        <%= form.date_field :date_report_completed, class: "free-text-input-big", data: { controller: "flatpickr", flatpickr_date_format: "Y-m-d", flatpickr_min_date: Time.zone.now } %>
      </div>

      <div class="form-group textOnInput mt-3">
        <%= form.label :premises_name %>
        <%= form.text_field :premises_name, class: "free-text-input-big" %>
      </div>

      <div class="form-group textOnInput mt-3">
        <%= form.label :street_address, "Street and No." %>
        <%= form.text_field :street_address, class: "free-text-input-big" %>
      </div>

      <div class="form-group textOnInput mt-3">
          <%= form.label :city %>
          <%= form.text_field :city, class: "free-text-input-big" %>
      </div>

      <div class="form-group textOnInput mt-3">
        <%= form.label :postcode %>
        <%= form.text_field :postcode, class: "free-text-input-big" %>
      </div>

      <div class="form-group textOnInput mt-3">
        <%= form.label :telephone_number %>
        <%= form.text_field :telephone_number, class: "free-text-input-big" %>
      </div>
      <div class="form-group textOnInput mt-3">
        <%= form.label :photos %>
        <%= form.file_field :photos, multiple: true, class: "free-text-input-big bg-white btn" %>
      </div>
    </div>
  </div>

    <div class="d-flex justify-content-between">
      <div>
        <%= link_to 'Back', companies_path, class: 'btn-big-dark' %>
      </div>
      <div class="justify-content-end">
        <%= form.button :submit, class: "btn-big"%>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/reports/action_plan.html.erb
<div class="container mt-5">
  <h1>Action Plan for <%= @report.premises_name %></h1>
  <div class="row">
    <div class="col-lg-12">
      <table class="table table-striped mt-5">
        <thead>
          <tr>
            <th scope="col">No.</th>
            <th scope="col">Fault</th>
            <th scope="col">Recommendation</th>
            <th scope="col">Priority</th>
            <th scope="col">Date</th>
            <th scope="col">Completed?</th>
          </tr>
        </thead>
        <tbody>
          <% num = 0 %>
          <% @report_questions.sort.each do |report_q| %>
            <tr>
              <th scope="row"><%= num += 1 %></th>
              <td class="p-3"><%= report_q.fault %></td>
              <td class="p-3"><%= report_q.recommendation %></td>
              <% if report_q.priority == "HIGH" %>
                <td class="bg-danger">HIGH</td>
              <% elsif report_q.priority == "MEDIUM" %>
                <td class="bg-warning">MEDIUM</td>
              <% elsif report_q.priority == "LOW" %>
                <td class="bg-info">LOW</td>
              <% else %>
                <td></td>
              <% end %>
              <%= form_with model: [@company, @report, report_q], method: :patch, id: "myform" do |f| %>
              <%# <%= simple_form_for [@company, @report, report_q], id: "myform" do |f| %>
                <td>
                  <%= f.date_field :date, data: { controller: "flatpickr", flatpickr_date_format: "Y-m-d", flatpickr_min_date: Time.zone.now }, readonly: current_user.client? ? true : false %>
                </td>
                <td>
                  <div class="form-check form-switch  ms-4">
                    <%= f.check_box :answer, class: "form-check-input",  type: "checkbox", id: "flexSwitchCheckDefault", readonly: current_user.client? ? true : false %>
                  </div>
                </td>
                <td class="p-3">
                <% if current_user.inspector? %>
                  <%= f.submit "Update Action", class: "btn", form: "myform" %>
                <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div>
      <%= link_to 'Back', company_report_path(@company, @report), class: 'btn-big-dark mt-5' %>
  </div>
</div>

app/views/reports/edit.html.erb
<div class="container mt-5">
  <h1>Edit <%= @report.premises_name %></h1>
<%= form_with(model: [@company, @report]) do |form| %>
    <% if @report.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@report.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @report.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>
    <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
      <div class="col-md-8">

        <div class="form-group textOnInput mt-3">
          <%= form.label :date_report_completed, "Date of assessment" %>
          <%= form.date_field :date_report_completed, class: "free-text-input-big", data: { controller: "flatpickr", flatpickr_date_format: "Y-m-d", flatpickr_min_date: Time.zone.now } %>
        </div>

        <div class="form-group textOnInput mt-3">
          <%= form.label :premises_name %>
          <%= form.text_field :premises_name, class: "free-text-input-big" %>
        </div>

        <div class="form-group textOnInput mt-3">
          <%= form.label :street_address, "Street Name & No"%>
          <%= form.text_field :street_address, class: "free-text-input-big"  %>
        </div>

        <div class="form-group textOnInput mt-3">
          <%= form.label :postcode %>
          <%= form.text_field :postcode, class: "free-text-input-big" %>
        </div>

        <div class="form-group textOnInput mt-3">
          <%= form.label :city %>
          <%= form.text_field :city, class: "free-text-input-big" %>
        </div>

        <div class="form-group textOnInput mt-3">
          <%= form.label :telephone_number %>
          <%= form.text_field :telephone_number, class: "free-text-input-big" %>
        </div>

        <div class="form-group textOnInput mt-3">
          <%= form.label :photos %>
          <%= form.file_field :photos, multiple: true, class: "free-text-input-big bg-white btn-photos" %>
        </div>
      </div>
    </div>

    <div class="d-flex justify-content-between">
      <div>
        <%= link_to 'Back', companies_path, class: 'btn-big-dark' %>
      </div>
      <div class="justify-content-end">
        <%= form.submit class: "btn-big"%>
      </div>
    </div>
  <% end %>

app/views/reports/fire_alarm.html.erb
<div class="container mt-5">
  <div>
    <div class="m-3">
      <% @names = [] %>
      <% @fault_array = [] %>
      <% @recommendation_array = [] %>
      <% @photos_array = [] %>
      <% @report_questions.sort.each do |report_q| %>
        <% @names << report_q.question.question_name %>
        <% @photos_array << report_q.photos %>
        <% @faults = report_q.question.faults %>
        <% @fault_names = [" "] %>
        <% @fault_recommendations = [" "] %>
        <% @faults.each do |fault| %>
          <% @fault_names << fault.fault_detail %>
          <% @fault_recommendations << fault.recommendation %>
        <% end %>
        <% @fault_array << @fault_names %>
        <% @recommendation_array << @fault_recommendations %>
      <% end %>
      <% num = -1 %>
      <%= form_with model: [@company, @report] do |p| %>
        <h2 class="mt-4 mb-4">Fire Alarm</h2>
        <%= p.fields_for :report_questions, @report_questions.sort do |f| %>
          <% num += 1 %>
          <div data-controller="question-card">
            <div class="d-flex justify-content-between m-2 pb-3 pt-3 mt-5">
              <div>
                <h5 class="card-title"><%= @names[num] %></h5>
              </div>
              <div class="field d-inline-flex">
                <div class="form-check form-switch">
                  <%# <%= f.label :answer, class: "form-check-label",  for: "flexSwitchCheckDefault" %>
                  <%= f.check_box :answer, class: "form-check-input",  type: "checkbox", id: "flexSwitchCheckDefault", data: { action: "change->question-card#hideContent" }, readonly: current_user.client? ? true : false %>
                </div>
              </div>
            </div>
            <div class="d-flex mt-3", data-question-card-target="contents">
              <div class="form-group textOnInput">
                <%= f.label :fault %>
                <% if current_user.client? %>
                  <%= f.text_area :fault, cols: 60, rows: 3, class: "free-text-input", readonly: true %>
                <% else %>
                  <%= f.select :fault, @fault_array[num] %>
                <% end %>
              </div>
              <div class="form-group textOnInput">
                <%= f.label :recommendation %>
                <% if current_user.client? %>
                  <%= f.text_area :recommendation, cols: 60, rows: 3, class: "free-text-input", readonly: true %>
                <% else %>
                  <%= f.select :recommendation, @recommendation_array[num], class: "" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="d-flex mt-4">
              <div class="form-group textOnInput">
                <%= f.label :priority %>
                <% if current_user.client? %>
                  <%= f.text_area :priority, cols: 10, rows: 1, class: "free-text-input", readonly: true %>
                <% else %>
                  <%= f.select :priority, [" ", "HIGH", "MEDIUM", "LOW"], class: "" %>
                <% end %>
              </div>
              <div class="form-group textOnInput">
                <%= f.label :date %>
                <%= f.date_field :date, class: "free-text-input", data: { controller: "flatpickr", flatpickr_date_format: "Y-m-d", flatpickr_min_date: Time.zone.now }, readonly: current_user.client? ? true : false %>
              </div>
              <div class="d-inline-flex">
              <div class="form-group textOnInput">
                <%= f.label :photos %>
                <%= f.file_field :photos, multiple: true, class: "free-text-input bg-white btn-photos", readonly: current_user.client? ? true : false %>
              </div>
            </div>
          </div>
          <br>
          <div class="mt-2 d-inline-flex">
            <% @photos_array[num].each do |photo| %>
              <% if photo %>
                <div class="me-5">
                  <%= cl_image_tag photo.key, width: 200, height: 200, crop: :fill %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
        <div data-controller="submit-all-forms">
          <div class="d-flex justify-content-between mt-5">
            <div>
              <%= link_to 'Back to Report', company_report_path(@company, @report), class: 'btn-big-dark' %>
            </div>
            <div class="justify-content-end">
              <% if current_user.inspector? %>
                <%= p.submit class: "btn-big"%>
              <% else %>
                <%= link_to 'Action plan', action_plan_path(@company, @report), class: 'btn-big' %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<div class="container mt-5">
  <h1>New Assessment</h1>
  <div>
    <%= render 'form', company: @company, report: @report %>
  </div>

</div>

app/views/reports/show.html.erb
<div class="container mt-5">
  <h1>Assessment for <%= @report.premises_name %></h1>

    <%= form_with(model: [@company, @report], data: { insert_in_list_target: "form", action: "submit->insert-in-list#send" }, local: true) do |form| %>
      <% if @report.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@report.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
          <% @report.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
        <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
          <div class="col-md-12">

            <div class="form-group textOnInput mt-3">
              <%= form.label :date_report_completed, "Date of Assessment" %>
              <% if @report.date_report_completed.present? %>
                <%= form.text_field :date_report_completed, class: "free-text-input-big", readonly: true %>
              <% else %>
                <p class="free-text-input">01/01/2000</p>
              <% end %>
            </div>

            <div class="form-group textOnInput mt-3">
              <%= form.label :inspector, "Assessor" %>
              <%= form.text_field :inspector, value: "#{@report.company.inspector.first_name} " "#{@report.company.inspector.last_name}", class: "free-text-input-big", readonly: true %>
            </div>

            <div class="form-group textOnInput mt-3">
              <%= form.label :address %>
              <%= form.text_field :address, value: "#{@report.street_address}, #{@report.city}, #{@report.postcode}", class: "free-text-input-big", readonly: true %>
            </div>
          </div>
          <div class="map col-md-4" data-controller="map"
            id="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
            style="margin-left: 20px;"
            >
          </div>
        </div>

        <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
          <div class="col-md-12">
            <h2>Jump to Report Category</h2>
            <br>
                  <%= link_to 'Action plan', action_plan_path(@company, @report), class: 'button-5' %>
                  <%= link_to 'Fire Alarm', fire_alarm_path(@company, @report), class: 'button-5'%>
                  <%= link_to 'Fire Training', fire_training_path(@company, @report), class: 'button-5' %>
                  <%= link_to 'Fire Extinguishers', fire_extinguishers_path(@company, @report), class: 'button-5' %>
          </div>
        </div>

        <div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
          <div class="col-md-12">
            <h2>Responsible Person</h2>

              <div class="form-group textOnInput mt-3">
                <%= form.label  :name, "Full Name" %>
                <%= form.text_field :name, value: "#{@report.company.client.first_name} " "#{@report.company.client.last_name}", class: "free-text-input-big", readonly: true %>
              </div>

              <div class="form-group textOnInput mt-3">
                <%= form.label :telephone_number,  "Phone Number" %>
                <%= form.text_field :inspector, value: "#{@report.company.client.telephone_number}", class: "free-text-input-big", readonly: true %>
              </div>

              <div class="form-group textOnInput mt-3">
                <%= form.label :email_address %>
                <%= form.text_field :email_address, value: "#{@report.company.client.email}", class: "free-text-input-big", readonly: true  %>
            </div>

            <% if @report.photos.any? %>
              <br>
              <h2>Photos</h2>
              <div class="d-inline-flex mt-1">
                <% @report.photos.each do |photo| %>
                  <div class="me-5">
                    <%= cl_image_tag photo.key, width: 200, height: 200, crop: :fill %>
                  </div>
                <% end %>
              </div>
            <% end %>

  <% end %>
  </div>
</div>

<div class="d-inline-flex justify-content-between ms-5 p-3 mt-5">
<div class="col-md-12">

  <h2 class="mb-4">Construction Details</h2>

    <div>
      <% @names = [] %>
      <% @fault_array = [] %>
      <% @recommendation_array = [] %>
      <% @photos_array = [] %>
      <% @report_questions.sort.each do |report_q| %>
        <% @names << report_q.question.question_name %>
        <% @photos_array << report_q.photos %>
        <% @faults = report_q.question.faults %>
        <% @fault_names = [" "] %>
        <% @fault_recommendations = [" "] %>
        <% @faults.each do |fault| %>
          <% @fault_names << fault.fault_detail %>
          <% @fault_recommendations << fault.recommendation %>
        <% end %>
        <% @fault_array << @fault_names %>
        <% @recommendation_array << @fault_recommendations %>
      <% end %>
      <% num = -1 %>
      <%= form_with model: [@company, @report], id: "myform" do |p| %>
        <div class="form-group textOnInput mt-">
            <%= p.label :construction_details %>
            <%= p.text_area :construction_details, cols: 115, rows: 6, class: "free-text-input", readonly: current_user.client? ? true : false%>

        </div>
        <div class="d-inline-flex">
          <div class="form-group textOnInput">
              <%= p.label :number_of_floors %>
              <%= p.text_field :number_of_floors, class: "free-text-input", readonly: current_user.client? ? true : false %>
          </div>
          <div class="form-group textOnInput">
              <%= p.label :floor_area %>
              <%= p.text_field :floor_area, class: "free-text-input", readonly: current_user.client? ? true : false %>
          </div>
          <div class="form-group textOnInput">
            <%= p.label :photos, "Photos" %>
            <%= p.file_field :photos, multiple: true, class: "free-text-input bg-white btn", readonly: current_user.client? ? true : false %>
          </div>
        </div>
          <h2 class="mt-3">Report</h2>
          <%= p.fields_for :report_questions, @report.report_questions.sort do |f| %>
            <% num += 1 %>
            <div class="p-3">
              <div data-controller="question-card">
                <div class="d-flex justify-content-between m-2 pb-3 pt-3 mt-3">
                  <div>
                    <h5 class="card-title"><%= @names[num] %></h5>
                  </div>
                  <div class="field d-inline-flex">
                    <div class="form-check form-switch">
                      <%# <%= f.label :answer, class: "form-check-label",  for: "flexSwitchCheckDefault" %>
                      <%= f.check_box :answer, class: "form-check-input",  type: "checkbox", id: "flexSwitchCheckDefault", data: { action: "change->question-card#hideContent" }, readonly: current_user.client? ? true : false%>
                    </div>
                  </div>
                </div>
                <div class="d-flex mt-3", data-question-card-target="contents">
                    <div class="form-group textOnInput">
                      <%= f.label :fault %>
                      <% if current_user.client? %>
                        <%= f.text_area :fault, cols: 60, rows: 3, class: "free-text-input", readonly: true %>
                      <% else %>
                        <%= f.select :fault, @fault_array[num] %>
                      <% end %>
                    </div>
                    <div class="form-group textOnInput">
                      <%= f.label :recommendation %>
                      <% if current_user.client? %>
                        <%= f.text_area :recommendation, cols: 60, rows: 3, class: "free-text-input", readonly: true %>
                      <% else %>
                        <%= f.select :recommendation, @recommendation_array[num], class: "" %>
                      <% end %>
                    </div>
                </div>
              </div>
              <div class="d-flex mt-4">
                <div class="form-group textOnInput">
                  <%= f.label :priority %>
                  <% if current_user.client? %>
                    <%= f.text_area :priority, cols: 10, rows: 1, class: "free-text-input", readonly: true %>
                  <% else %>
                    <%= f.select :priority, [" ", "HIGH", "MEDIUM", "LOW"], class: "" %>
                  <% end %>
                </div>
                <div class="form-group textOnInput ms-4">
                  <%= f.label :date %>
                  <%= f.date_field :date, class: "free-text-input", data: { controller: "flatpickr", flatpickr_date_format: "Y-m-d", flatpickr_min_date: Time.zone.now }, readonly: current_user.client? ? true : false %>
                </div>
                <div class="d-inline-flex">
                  <div class="form-group textOnInput ms-5">
                    <%= f.label :photos %>
                    <%= f.file_field :photos, multiple: true, class: "free-text-input bg-white btn-photos", readonly: current_user.client? ? true : false %>
                  </div>
                </div>
              </div>
              <br>
              <div class="mt-2 d-inline-flex">
                <% @photos_array[num].each do |photo| %>
                  <% if photo %>
                    <div class="me-5">
                      <%= cl_image_tag photo.key, width: 200, height: 200, crop: :fill %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>

        <div>
          <div class="d-flex justify-content-between mt-5">
            <div>
              <%= link_to 'Back to Company', company_path(@report.company), class: 'btn-big-dark' %>
            </div>
            <div class="justify-content-end">
              <% if current_user.inspector? %>
                <%= p.submit class: "btn-big", form: "myform"%>
              <% else %>
                <%= link_to 'Action plan', action_plan_path(@company, @report), class: 'btn-big' %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>